server:
  port: 9003

spring:
  application:
    name: FAVORITE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
  instance:
    hostname: localhost