server:
  port: 9002

spring:
  application:
    name: FAVORITE-CITIES

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
  instance:
    hostname: localhost
